import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Image from 'next/image'
import DemoImage from './demo-image.jpg'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image src={DemoImage} width="445" height="687" alt="demo-image" />
        <p>Image by <a href="https://www.pexels.com/de-de/foto/stadt-wahrzeichen-gebaude-architektur-7224170/">Simon Gough</a></p>
      </main>

    </div>
  )
}

export default Home
